### ISSUE TITLE
Mod Does Not Generate Config

### ISSUE THREAD

**Issue by Amaxter** [ezterry/JsonRecipeEdit#1]
Title, using Forge 2229 on 1.11.2

**Comment by ezterry** [comment]
There is no config proper.

That said as there is obviously confustion I can auto generate a default script that has a link to the sample on the wiki

https://github.com/ezterry/JsonRecipeEdit/wiki/Sample1

The wiki also has links to json schema to help validate the json prior to loading a pack.

**Comment by ezterry** [comment]
generation of (empty) json added in v0.2
